apiVersion: v1
kind: ReplicationController
metadata:
  name: spkr-redis-server-v000
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    replication-controller: spkr-redis-server-v000
  template:
    metadata:
      labels:
        replication-controller: spkr-redis-server-v000
        load-balancer-spkr-redis-server: "true"
    spec:
      containers:
      - name: redis-server
        image: gcr.io/kubernetes-spinnaker/redis-cluster:v1
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
