apiVersion: v1
kind: ReplicationController
metadata:
  name: spkr-redis-sentinel-v000
  namespace: spinnaker
spec:
  replicas: 1
  selector:
    replication-controller-prime: spkr-redis-sentinel-v000
  template:
    metadata:
      labels:
        replication-controller: spkr-redis-sentinel-v000
        replication-controller-prime: spkr-redis-sentinel-v000
        load-balancer-spkr-redis-sentinel: "true"
    spec:
      containers:
      - name: redis-sentinel
        image: gcr.io/kubernetes-spinnaker/redis-cluster:v1
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
