server:
  port: ${services.igor.port:8088}
  address: ${services.igor.host:localhost}

jenkins:
  enabled: ${services.jenkins.enabled:false}
  masters:
    - name: ${services.jenkins.defaultMaster.name}
      address: ${services.jenkins.defaultMaster.baseUrl}
      username: ${services.jenkins.defaultMaster.username}
      password: ${services.jenkins.defaultMaster.password}

redis:
  connection: ${services.redis.connection:redis://localhost:6379}
  

# services:
#  clouddriver:
#    baseUrl: ${services.clouddriver.baseUrl}
#  echo:
#    This is recursive
#    baseUrl: ${services.echo.baseUrl}
