clouddriver: 
  container_name: clouddriver
  env_file: ./compose.env
  environment: 
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  image: spinnaker/clouddriver
  links: 
    - redis
  ports: 
    - "7002:7002"
  volumes: 
    - "../../config:/root/.spinnaker"
    - "~/.aws:/root/.aws"
echo: 
  container_name: echo
  env_file: ./compose.env
  environment: 
    - "FRONT50_BASEURL=http://$DOCKER_IP:8080"
  image: spinnaker/echo
  ports: 
    - "8089:8089"
  volumes: 
    - "../../config:/root/.spinnaker"
front50: 
  container_name: front50
  env_file: ./compose.env
  image: spinnaker/front50
  ports: 
    - "8080:8080"
  volumes: 
    - "../../config:/root/.spinnaker"
frontend: 
  container_name: deck
  environment: 
    - "API_HOST=$DOCKER_IP:8084"
    - DECK_HOST=0.0.0.0
    - DECK_PORT=9000
    - PROTOCOL=http
  image: spinnaker/deck
  ports: 
    - "9000:9000"
gate: 
  container_name: gate
  env_file: ./compose.env
  environment: 
    - "CLOUDDRIVER_BASE_URL=http://clouddriver:7002"
    - "ECHO_BASEURL=http://echo:8089"
    - "FRONT50_BASEURL=http://front50:8080"
    - "OORT_BASEURL=http://clouddriver:8083"
    - "MORT_BASEURL=http://clouddriver:8083"
    - "IGOR_BASEURL=http://igor:8088"
    - "ORCA_BASEURL=http://orca:8083"
  image: spinnaker/gate
  links: 
    - redis
    - clouddriver
    - echo
    - front50
    - igor
    - orca
  ports: 
    - "8084:8084"
  volumes: 
    - "../../config:/root/.spinnaker"
igor: 
  container_name: igor
  env_file: ./compose.env
  environment: 
    - "SERVICES_ECHO_BASEURL=http://echo:8089"
  image: spinnaker/igor
  links: 
    - redis
    - echo
  ports: 
    - "8088:8088"
  volumes: 
    - "../../config:/root/.spinnaker"
orca: 
  container_name: orca
  env_file: ./compose.env
  environment: 
    - "CLOUDDRIVER_BASE_URL=http://clouddriver:7002"
    - "ECHO_BASEURL=http://echo:8089"
    - "FRONT50_BASEURL=http://front50:8080"
    - "IGOR_BASEURL=http://igor:8088"
  image: spinnaker/orca
  links: 
    - redis
    - clouddriver
    - echo
    - front50
    - igor
  ports: 
    - "8083:8083"
  volumes: 
    - "../../config:/root/.spinnaker"
redis: 
  container_name: redis
  expose: 
    - "6379"
  image: redis