name: Build Cop

on:
  schedule:
  - cron: "*/5 * * * *"
  # - cron: 0 11 * * MON-FRI

jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
    - id: assigned
      uses: "lee-dohm/last-assigned@76c68f419feb4d70efaae2a83b2f04bba8977eb1"
      with:
        query: 'label:build-cop-rotation'
        token: ${{ secrets.SPINNAKERBOT_GHA_BUILD_COP_TOKEN }}
    - id: rotation
      uses: lee-dohm/team-rotation@v1
      with:
        teamName: "@spinnaker/build-cops"
        token: ${{ secrets.SPINNAKERBOT_GHA_BUILD_COP_TOKEN }}
        last: ${{ steps.assigned.outputs.last }}
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.SPINNAKERBOT_GHA_BUILD_COP_TOKEN }}
      with:
        filename: .github/build-cop-template.md
        assignees: ${{ steps.rotation.outputs.next }}
